app = 'homed-server-google'
primary_region = 'cdg'

[env]
  DATABASE_URL = '/data/user.db'
  GOOGLE_APPLICATION_CREDENTIALS = '/tmp/gcloud/key.json'
  DEBUG = '*,-router*,-require-in-the-middle,-send,-body-parser*,-esbuild-register,-express-session,-homed:*:debug'
  DEBUG_HIDE_DATE = "1"
  NODE_ENV = 'production'

[[files]]
  secret_name = 'GOOGLE_APPLICATION_CREDENTIALS_JSON'
  guest_path = '/tmp/gcloud/key.json'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '5GB'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['http', 'tls']

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 8042

  [[services.ports]]
    port = 8042
    internal_port = 8042

  [[services.tcp_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
